### ISSUE TITLE
crawl fails after completion of zora-call-tokenmetadatauri with errors

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#117]
```
(node:18413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20483)
(node:18413) UnhandledPromiseRejectionWarning: Error: TypeError: Only absolute URLs are supported
    at Worker.<anonymous> (file:///Users/timdaub/Projects/neume-network/core/src/strategies/src/lifecycle.mjs:149:13)
    at Worker.emit (events.js:400:28)
    at MessagePort.<anonymous> (internal/worker.js:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
(node:18413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20484)
```

**Comment by TimDaub** [comment]
should be fixed
