### ISSUE TITLE
zora-call-tokenuri doesn't stop properly

### ISSUE THREAD

**Issue by il3ven** [neume-network/strategies#152]
### How to replicate?

In lifecycle.mjs emit the following message to run only zora-call-tokenuri.

```
lch.emit("message", {
    type: "transformation",
    version: "0.0.1",
    name: "zora-call-tokenuri",
    args: [],
});
```

**Observe the problem:** 

```
neume-network-strategies:lifecycle {"type":"extraction","version":"0.1.0","name":null,"args":["/Users/vaibhav/repos/il3ven/music-os/core/data/zora-call-tokenuri-transformation"]} +0ms
  neume-network-strategies:lifecycle [
  neume-network-strategies:lifecycle   {
  neume-network-strategies:lifecycle     instancePath: '/name',
  neume-network-strategies:lifecycle     schemaPath: '#/properties/name/type',
  neume-network-strategies:lifecycle     keyword: 'type',
  neume-network-strategies:lifecycle     params: { type: 'string' },
  neume-network-strategies:lifecycle     message: 'must be string'
  neume-network-strategies:lifecycle   }
  neume-network-strategies:lifecycle ] +0ms
file:///Users/vaibhav/repos/il3ven/music-os/core/src/strategies/src/lifecycle.mjs:94
    throw new ValidationError(
          ^

ValidationError: Found 1 or more validation error when checking lifecycle message.
    at check (file:///Users/vaibhav/repos/il3ven/music-os/core/src/strategies/src/lifecycle.mjs:94:11)
    at LifeCycleHandler.<anonymous> (file:///Users/vaibhav/repos/il3ven/music-os/core/src/strategies/src/lifecycle.mjs:163:5)
    at LifeCycleHandler.emit (node:events:527:28)
    at file:///Users/vaibhav/repos/il3ven/music-os/core/src/strategies/src/lifecycle.mjs:169:49
    at Array.forEach (<anonymous>)
    at LifeCycleHandler.<anonymous> (file:///Users/vaibhav/repos/il3ven/music-os/core/src/strategies/src/lifecycle.mjs:169:24)
```

### Possible reason

When zora-call-tokenuri ends ` {"type":"extraction","version":"0.1.0","name":null,"args":["/Users/vaibhav/repos/il3ven/music-os/core/data/zora-call-tokenuri-transformation"]}` is emitted. No message is expected to be emitted.

I believe the problem is due this line. 

https://github.com/neume-network/strategies/blob/490c71e0accfde076ec225a9da735ea089f05cac/src/strategy-factories/decode-solidity-hex-string-factory/transformer.mjs#L15-L19

---

I can create a quick PR for this.

**Comment by TimDaub** [comment]
just found the same problem and fixed it in feat/music-os-delivery but thanks for investigating :)
