### ISSUE TITLE
There are cases when soundxyz-get-tokenuri-transformation isn't started but music-os-accumulator already attempts running

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#170]
- full run: https://github.com/neume-network/data/runs/7279036688?check_suite_focus=true

extract from logs
```
2022-07-11T12:05:13.2303747Z 2022-07-11T12:05:13.230Z neume-network-strategies:lifecycle Received new lifecycle message: "{"type":"extraction","version":"0.0.1","name":"music-os-accumulator","args":[]}"
2022-07-11T12:05:13.2305024Z 2022-07-11T12:05:13.230Z neume-network-strategies:lifecycle Starting extractor with name "music-os-accumulator" with fn "init" and params "[]"
2022-07-11T12:05:13.4766062Z events.js:377
2022-07-11T12:05:13.4766714Z       throw er; // Unhandled 'error' event
2022-07-11T12:05:13.4767003Z       ^
2022-07-11T12:05:13.4767134Z 
2022-07-11T12:05:13.4767692Z Error: ENOENT: no such file or directory, open '/home/runner/work/data/data/data/soundxyz-get-tokenuri-transformation'
2022-07-11T12:05:13.4768302Z Emitted 'error' event on ReadStream instance at:
2022-07-11T12:05:13.4768683Z     at internal/fs/streams.js:126:14
2022-07-11T12:05:13.4769040Z     at FSReqCallback.oncomplete (fs.js:180:23) {
2022-07-11T12:05:13.4769385Z   errno: -2,
2022-07-11T12:05:13.4769657Z   code: 'ENOENT',
2022-07-11T12:05:13.4769957Z   syscall: 'open',
2022-07-11T12:05:13.4770445Z   path: '/home/runner/work/data/data/data/soundxyz-get-tokenuri-transformation'
2022-07-11T12:05:13.4770796Z }
2022-07-11T12:05:13.4917709Z npm ERR! code ELIFECYCLE
2022-07-11T12:05:13.4920904Z npm ERR! errno 1
2022-07-11T12:05:13.4951519Z npm ERR! neume-network-core@0.0.1 dev: `DEBUG=neume-network-* node ./src/boot.mjs`
2022-07-11T12:05:13.4953399Z npm ERR! Exit status 1
2022-07-11T12:05:13.4955117Z npm ERR! 
2022-07-11T12:05:13.4956836Z npm ERR! Failed at the neume-network-core@0.0.1 dev script.
2022-07-11T12:05:13.4958602Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-07-11T12:05:13.5000006Z 
2022-07-11T12:05:13.5002416Z npm ERR! A complete log of this run can be found in:
2022-07-11T12:05:13.5004283Z npm ERR!     /home/runner/.npm/_logs/2022-07-11T12_05_13_496Z-debug.log
2022-07-11T12:05:13.5044576Z ##[error]Process completed with exit code 1.

```

**Comment by TimDaub** [comment]
I couldn't find any reasonable error message and so it makes me believe that this error could have arisen from zora-get-tokenuri and zora-get-tokenmetadatauri being faster than soundxyz-get-tokenuri and hence calling music-os-accumulator too early e.g. #168 would fix this. Investigating further...

**Comment by TimDaub** [comment]
grep "Starting\|Ending" 7_Run\ indexer.txt > order.txt

```
2022-07-11T08:54:24.1131475Z 2022-07-11T08:54:24.113Z neume-network-strategies:lifecycle Starting extractor with name "web3subgraph" with fn "init" and params "[]"
2022-07-11T08:54:24.2986507Z 2022-07-11T08:54:24.297Z neume-network-extraction-worker:worker Starting as worker thread with queue options: "{"concurrent":2}
2022-07-11T08:54:34.9024456Z 2022-07-11T08:54:34.902Z neume-network-strategies:lifecycle Ending extractor strategy with name "web3subgraph"
2022-07-11T08:54:34.9034174Z 2022-07-11T08:54:34.903Z neume-network-strategies:lifecycle Starting extractor with name "web3subgraph" with fn "init" and params "null"
2022-07-11T08:54:34.9047457Z 2022-07-11T08:54:34.904Z neume-network-strategies:lifecycle Starting transformer strategy with name "web3subgraph"
2022-07-11T08:54:34.9893767Z 2022-07-11T08:54:34.989Z neume-network-strategies:lifecycle Ending transformer strategy with name "web3subgraph"
2022-07-11T08:54:35.0102173Z 2022-07-11T08:54:35.009Z neume-network-strategies:lifecycle Starting extractor with name "soundxyz-call-tokenuri" with fn "init" and params "["/home/runner/work/data/data/data/web3subgraph-transformation"]"
2022-07-11T08:54:35.0111281Z 2022-07-11T08:54:35.010Z neume-network-strategies:lifecycle Starting extractor with name "zora-call-tokenuri" with fn "init" and params "["/home/runner/work/data/data/data/web3subgraph-transformation"]"
2022-07-11T08:54:35.0114000Z 2022-07-11T08:54:35.010Z neume-network-strategies:lifecycle Starting extractor with name "zora-call-tokenmetadatauri" with fn "init" and params "["/home/runner/work/data/data/data/web3subgraph-transformation"]"
2022-07-11T10:00:00.4077274Z 2022-07-11T10:00:00.407Z neume-network-strategies:lifecycle Ending extractor strategy with name "zora-call-tokenuri"
2022-07-11T10:00:00.4080100Z 2022-07-11T10:00:00.407Z neume-network-strategies:lifecycle Starting extractor with name "zora-call-tokenuri" with fn "init" and params "null"
2022-07-11T10:00:00.4093174Z 2022-07-11T10:00:00.409Z neume-network-strategies:lifecycle Starting transformer strategy with name "zora-call-tokenuri"
2022-07-11T10:00:01.5300105Z 2022-07-11T10:00:01.529Z neume-network-strategies:lifecycle Ending transformer strategy with name "zora-call-tokenuri"
2022-07-11T10:50:09.5840708Z 2022-07-11T10:50:09.583Z neume-network-strategies:lifecycle Ending extractor strategy with name "zora-call-tokenmetadatauri"
2022-07-11T10:50:09.5844380Z 2022-07-11T10:50:09.584Z neume-network-strategies:lifecycle Starting extractor with name "zora-call-tokenmetadatauri" with fn "init" and params "null"
2022-07-11T10:50:09.5857099Z 2022-07-11T10:50:09.585Z neume-network-strategies:lifecycle Starting transformer strategy with name "zora-call-tokenmetadatauri"
2022-07-11T10:50:10.6866087Z 2022-07-11T10:50:10.686Z neume-network-strategies:lifecycle Ending transformer strategy with name "zora-call-tokenmetadatauri"
2022-07-11T10:50:10.7112663Z 2022-07-11T10:50:10.710Z neume-network-strategies:lifecycle Starting extractor with name "zora-get-tokenuri" with fn "init" and params "["/home/runner/work/data/data/data/zora-call-tokenmetadatauri-transformation"]"
2022-07-11T12:05:12.9082513Z 2022-07-11T12:05:12.908Z neume-network-strategies:lifecycle Ending extractor strategy with name "zora-get-tokenuri"
2022-07-11T12:05:12.9085148Z 2022-07-11T12:05:12.908Z neume-network-strategies:lifecycle Starting extractor with name "zora-get-tokenuri" with fn "init" and params "null"
2022-07-11T12:05:12.9096984Z 2022-07-11T12:05:12.909Z neume-network-strategies:lifecycle Starting transformer strategy with name "zora-get-tokenuri"
2022-07-11T12:05:13.1684313Z 2022-07-11T12:05:13.168Z neume-network-strategies:lifecycle Ending transformer strategy with name "zora-get-tokenuri"
2022-07-11T12:05:13.2305024Z 2022-07-11T12:05:13.230Z neume-network-strategies:lifecycle Starting extractor with name "music-os-accumulator" with fn "init" and params "[]"

```
