### ISSUE TITLE
Parsing zora amulets throws error during crawl

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#171]
- run: https://github.com/neume-network/data/runs/7279036688?check_suite_focus=true

extract from logs
```
2022-07-11T11:07:13.5414699Z (node:1917) UnhandledPromiseRejectionWarning: Error: Error: Encountered error when trying to parse JSON body result: "{"description":"JelliedOwl believes this to be the first WSB poem, and likely WSB art in general, minted on a Zora token. (Buyer is responsible for checking!)
2022-07-11T11:07:13.5415570Z Hand crafted, machine checked. 
2022-07-11T11:07:13.5416773Z This is an amulet, a short poem with a lucky SHA-256 hash, explained here: https://text.bargains/amulet/
2022-07-11T11:07:13.5417822Z This poem's hash contains the sequence 8888, which means its rarity is COMMON. Perhaps it will help GME to reach $8888? *This is not financial advice - I'm just an art-loving idiot!*
2022-07-11T11:07:13.5419566Z Here is a record of the 8888lb carbon offset purchased in this poem's name: https://dashboard.cloverly.com/receipt/20210301-3e35daf1512c3b5ffbc5d45fb7d3cabf","mimeType":"text/plain","name":"Ode to r/wallstreetbets","rarity":"common","version":"amulet-20210221"}", error: "SyntaxError: Unexpected token 
2022-07-11T11:07:13.5420273Z  in JSON at position 158"
2022-07-11T11:07:13.5420734Z     at Worker.<anonymous> (file:///home/runner/work/data/data/src/strategies/src/lifecycle.mjs:172:13)
2022-07-11T11:07:13.5421147Z     at Worker.emit (events.js:400:28)
2022-07-11T11:07:13.5421524Z     at MessagePort.<anonymous> (internal/worker.js:236:53)
2022-07-11T11:07:13.5422001Z     at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
2022-07-11T11:07:13.5422541Z     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
2022-07-11T11:07:13.5424282Z (node:1917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1105)
2022-07-11T11:07:13.5431609Z 2022-07-11T11:07:13.540Z neume-network-extraction-worker:worker Panic in queue with taskId "5d4582a5-85d7-4b00-be77-cdfe7b265059", error "{"type":"https","commissioner":"zora-get-tokenuri","version":"0.0.1","options":{"url":"https://neume.infura-ipfs.io/ipfs/bafybeiahjg6rsohw246izepsxpfy4zf2ptyhv4ftvikbhsgsdqkfu5kd3a","method":"GET","headers":{"Authorization":"***"},"timeout":3000},"results":null,"error":"Error: Encountered error when trying to parse JSON body result: \"{\"description\":\"JelliedOwl believes this to be the first WSB poem, and likely WSB art in general, minted on a Zora token. (Buyer is responsible for checking!)\nHand crafted, machine checked. \nThis is an amulet, a short poem with a lucky SHA-256 hash, explained here: https://text.bargains/amulet/\nThis poem's hash contains the sequence 8888, which means its rarity is COMMON. Perhaps it will help GME to reach $8888? *This is not financial advice - I'm just an art-loving idiot!*\nHere is a record of the 8888lb carbon offset purchased in this poem's name: https://dashboard.cloverly.com/receipt/20210301-3e35daf1512c3b5ffbc5d45fb7d3cabf\",\"mimeType\":\"text/plain\",\"name\":\"Ode to r/wallstreetbets\",\"rarity\":\"common\",\"version\":\"amulet-20210221\"}\", error: \"SyntaxError: Unexpected token \n in JSON at position 158\""}" and stats "{"elapsed":1022463}"
```

**Comment by TimDaub** [comment]
This log exists in crawls that passed neume-network/data, so it isn't taking down the entire process: https://github.com/neume-network/data/actions/runs/2644784880
